title: Giovanni Montino Pelagi,  PhD
theme: minima
author:
  name: Giovanni Montino Pelagi
  email: giovanni.montino.pelagi@gmail.com
description: Bridging engineering & medicine (and skiing) since 1996
