title: Giovanni Montino Pelagi,  PhD
theme: minima
author:
  name: Giovanni Montino Pelagi
  email: giovanni.montino.pelagi@gmail.com
description_line1: Bridging engineering & medicine (and skiing)
description_line2: since 1996
